### ISSUE TITLE
Turkish Translate & Mission of Spy Probes & Market & Admin Panel

### ISSUE THREAD

**Issue by Atesel** [Yaro2709/New-Star#61]
Hello

1 - Whenever I have time, I work on the script and translate it into Turkish. I can send you the file I created for language support.

2 - No Assignment from Fleet (Filo) Division to Espionage Probes.

![image](https://user-images.githubusercontent.com/108869521/177766699-adf7a275-3d5a-40dc-ac92-c8d21215b867.png)

3 - I cannot cancel the Offers I Have Created in the Marketplace.

![image](https://user-images.githubusercontent.com/108869521/177766912-2158ac68-1faa-4b90-bc5c-b003fcb697f9.png)

4 - Sometimes I get the following errors in the admin section.

[error.log](https://github.com/Yaro2709/New-Star/files/9063359/error.log)

**Comment by Ronneraz** [comment]
I have fixed the SPY's BUG and some other issus, you can see them in pull requests and my another issus.
And i am translate it into Chinese and finished 95%，i find some text are writed in html not in php. so i'm creat a list of them
in【\styles\theme\nsc\templates\game\page.alliance.issue.tpl】
`<input type="button" onClick="UserList.set(this.form.regexp.value)" value="Фильтр">
            <input type="button" onClick="UserList.reset();this.form.regexp.value=''" value="Отменить">`
in【\styles\theme\nsc\templates\game\page.fleetStep2.default.tpl】
`<span class="fleetstep2-3">{$LNG.fl_resources} <a style="float:right; color:#666;" href="javascript:maxResources()">Все ресурсы</a></span>`
in【\language\zh\FLEET.php】and【\language\zh\CUSTOM.php】,lost a name【`$LNG['sys_expe_found_container_1'] `】
in【\styles\theme\nsc\templates\game\page.shipyard.default.tpl】，【 `<span class="shipyardd2">(в процессе)</span>`】
in【\scripts\game\delivery.js】，line13【alert('???');】should【alert('no select any resources');】
in【\styles\theme\nsc\templates\adm\page.sendmessages.default.tpl】，line33 should be【`<label for="subject">{$LNG.ma_subject}</label>`】
in【\styles\theme\nsc\templates\game\page.playerCard.default.tpl】，line23 should be【`{if $allyname}[<a href="#" onclick="parent.location = 'game.php?page=alliance&amp;mode=info&amp;id={$allyid}';return false;" class="playercrd17">{$allyname}]</a>{else}{/if}`】
in【\styles\theme\nsc\templates\game\page.search.result.default.tpl】，【b.gif→iconav/friend.png】【m.gif→iconav/mesages.png】

I hope these can help you :)

**Comment by Atesel** [comment]
Hi

Thank you. Some Minor Bugs Fixed But My Big Problems Still Continuing.

**- I can't send a spy probe. (Fleet)**

![Ekran görüntüsü 2022-07-18 112041](https://user-images.githubusercontent.com/108869521/179472289-1fb7d130-bb54-463e-9c72-b5fc7c74ffda.png)
![Ekran görüntüsü 2022-07-18 112226](https://user-images.githubusercontent.com/108869521/179472293-d6550f30-f67b-48c7-984f-408238c7dff7.png)




**- The Error Message I Get In The Admin Panel Continues. Also the Interface Causes Problems in Mozilla and Safari.**


![Ekran görüntüsü 2022-07-18 105812](https://user-images.githubusercontent.com/108869521/179471280-ea200e57-dfa3-47db-95a3-f32376887328.png)
![Ekran görüntüsü 2022-07-18 105813](https://user-images.githubusercontent.com/108869521/179471285-ceaf32ab-c0a2-49fd-956f-4fb1a9ce1929.jpg)

**Comment by Ronneraz** [comment]
The BUG for the SPY is caused by the space in install.sql,you can fix the file and update the Database or edit the sql and reinstall the game to fixt it，and there's 3 ships with the same bug. i'm fixed them in this requests.

> https://github.com/Yaro2709/New-Star/pull/57


I'm sorry for the Admin Panel BUG i find it but i don't know how to fix it,i'm now use the chrome and it works. Maybe you need connect the Yaro

**Comment by bin9yuz79** [comment]
@Atesel Dil dosyasını tamamladıysan paylaşabilir misin? Mümkün mü?
